// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdzsgstdndbebdatijav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkenNnc3RkbmRiZWJkYXRpamF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3ODM0NzcsImV4cCI6MjEwMTM1OTQ3N30.Mrrm96pWWeKoEhaXSwm2DGMqMTGnj33BQkPqu5c4Yeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});